### PR TITLE
Added Repositories section

### PR DESCRIPTION
**Pull request by kylejbrk**
I added a Repositories section which includes my extensions repository found here: https://github.com/kylejbrk/standard-notes-open-extended

### CODE REVIEW

**Comment by jrabensc** [comment]
I'm not exactly sure what this is doing. Can this be used to use the extensions without paying for them?

**Comment by jonhadfield** [comment]
> I'm not exactly sure what this is doing. Can this be used to use the extensions without paying for them?

Ditto. Would like to understand what this provides.

**Comment by kylejbrk** [comment]
@jrabensc 
Yes, at least most of them.

It hosts official Standard Notes extensions via Github Pages. It also checks for updates daily (via Github Actions) which always gives users the most up to date extensions.

The instructions for adding the Repo is in the README. It's a similar process to most of the extensions you have listed, except you need to paste the endpoint in the Extended Activation Code textbox instead of the Import Extension textbox. If you have suggestions for how I can make my instructions/description more clear please let me know.

**Comment by jonhadfield** [comment]
@kylejbrk It sounds like a way of effectively bypassing the paywall that SN use to fund the development of the application. I may well be wrong, but will check with SN to see if they’re ok with us promoting this tool.

**Comment by jrabensc** [comment]
We checked with the author of Standard Notes and introduced a new policy for the list:
> This list will only provide and promote original creations and not any material related to re-hosting creations of Standard Notes.

Hence, this PR will not be merged.

**Comment by kylejbrk** [comment]
Curious, would you guys be interested in a similar project that only hosts community made content (i.e. themes and components listed in your repo)?

**Comment by jonhadfield** [comment]
Hi @kylejbrk, it depends what you mean by similar. The spirit of this repo is to host and promote individual, original, creations that people can check out and import. I'm not keen on including bundles, especially if they're from multiple different authors, as I think it means the average user is less likely to know what they're installing.

**Pull request closed without merging**
